### ISSUE TITLE
Local development setup throws `Cannot read properties of undefined (reading 'querySelectorAll')`

### ISSUE THREAD

**Issue by dmohns** [EnAccess/micropowermanager#179]
In the local development environment it's quite common to throw 

```
Cannot read properties of undefined (reading 'querySelectorAll')
TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at VueComponent.calculateTabPos (webpack-internal:///./node_modules/vue-material/dist/vue-material.js:14257:62)
    at VueComponent.callResizeFunctions (webpack-internal:///./node_modules/vue-material/dist/vue-material.js:14270:12)
    at MutationObserver.eval (webpack-internal:///./node_modules/vue-material/dist/vue-material.js:14280:16)
```

For example, when opening `Reports`

**Comment by munyanezaarmel** [comment]
I am closing this issue as the error no longer appears when opening the Reports section. Previously, I encountered this error, for instance, when loading certain pages. However, it is no longer present, even when accessing Reports.

If there are any specific areas that need to be checked, please let me know, and I will revisit the issue if necessary
